booking_jumpstart/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("jumpstart.urls")),
    path('accounts/', include('allauth.urls')),
]

jumpstart/urls.py
from django.urls import path, reverse_lazy

# View-related imports
from . import views
from django.contrib.auth import views as reset_views

# Django settings-related imports
from django.conf import settings
from django.conf.urls.static import static

# Form-related imports
from .forms import CustomPasswordResetForm, CustomSetPasswordForm


app_name = 'jumpstart'
urlpatterns = [
    path('login/', views.LoginSignup.as_view(), name='login'),
    path('logout/', views.UserLogout.as_view(), name='logout'),
    path('', views.Welcome.as_view(), name='welcome'),
    path('booking/create/', views.CustomerBooking.as_view(), name='create_booking'),
    path('view_profile/', views.Profile.as_view(), name='view_profile'),
    path('view_profile/update/', views.CustomerUpdateView.as_view(), name='profile_update'),
    path('search/<int:id>', views.Search.as_view(), name='search'),

    # forgot password views
    path('password_reset/',
         reset_views.PasswordResetView.as_view(form_class=CustomPasswordResetForm,
                                               success_url=reverse_lazy('jumpstart:password_reset_done')),
         name='password_reset',
        ),
    path('password_reset/done/',
         reset_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         reset_views.PasswordResetConfirmView.as_view(form_class=CustomSetPasswordForm,
                                                    template_name='registration/password_reset_confirm.html',
                                                      success_url=reverse_lazy('jumpstart:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/', reset_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jumpstart/models.py
# Python built-in modules
import datetime
import re

# Django modules
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import lower
from django.utils import timezone

# Local modules
from .city_n_provinces_n_edu import CITY_CHOICES, PROVINCE_CHOICES, UNIVERSITY_CHOICES, EVENT_TIME_CHOICES

# Create your models here.


class Customer(User):
    class Meta:
        ordering = ['first_name']
        verbose_name_plural = 'customer'

    user = models.OneToOneField(User, parent_link=True, related_name='customer', on_delete=models.CASCADE, default=None)
    profile_image = models.ImageField(upload_to='images/profile/', default='profile/gojo.png')

    def __str__(self):
        return self.username


class Event(models.Model):
    SINGLE_EVENT = 'single'
    MULTI_EVENT = 'multi'
    EVENT_TYPE_CHOICES = [
        (SINGLE_EVENT, 'single-event'),
        (MULTI_EVENT, 'multi-event'),
    ]
    name = models.CharField(max_length=100)
    event_type = models.CharField(max_length=10, choices=EVENT_TYPE_CHOICES)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    timings = models.CharField(max_length=100)
    short_description = models.CharField(max_length=200)
    additional_info = models.TextField(blank=True)
    keywords = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        # Extract the time ranges from the string using regex
        matches = re.findall(r':\s+(\d{1,2}(?:am|pm)-\d{1,2}(?:am|pm))', self.timings)
        days = "Monday Tuesday Wednesday Thursday Friday Saturday Sunday"

        # print(self.name, matches)

        # Generate the times for each range
        times = []
        for match in matches:
            time_range = match
            start_time, end_time = time_range.split('-')
            start_time = datetime.datetime.strptime(start_time, "%I%p")
            end_time = datetime.datetime.strptime(end_time, "%I%p")
            curr_time = start_time
            while curr_time <= end_time:
                times.append(lower(curr_time.strftime("%I%p")))
                curr_time += datetime.timedelta(hours=1)
        times.append(days)
        times = set(times)
        # Join the list of times into a single string separated by space
        times_str = " ".join(times)

        # Split name, short_description, and additional_info fields into words
        words = []
        for field in [self.name, self.short_description, self.additional_info]:
            words += field.split()
        # Save the words as keywords
        self.keywords = ' '.join(set(words))
        self.keywords = self.keywords + ' ' + times_str
        super().save(*args, **kwargs)


class Ticket(models.Model):
    RESERVATION_CHOICES = [
        ('single-event', 'Single Event'),
        ('multi-event', 'Multi Event')
    ]
    reserved_event = models.ForeignKey(Event, on_delete=models.CASCADE)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    event_type = models.CharField(max_length=12, choices=RESERVATION_CHOICES)
    reservation_date = models.DateField()
    reservation_time = models.CharField(max_length=12, choices=EVENT_TIME_CHOICES)
    is_student = models.BooleanField(default=False)
    university = models.CharField(max_length=50, choices=UNIVERSITY_CHOICES, default='University of Windsor')
    adult_tickets = models.IntegerField(default=0)
    children_tickets = models.IntegerField(default=0)
    total_price = models.DecimalField(max_digits=6, decimal_places=2)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100, choices=CITY_CHOICES)
    province = models.CharField(max_length=50, choices=PROVINCE_CHOICES)
    phone_number = models.CharField(max_length=10)
    ticket_id = models.CharField(max_length=20)
    transaction_id = models.CharField(max_length=50)
    transaction_timestamp = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return f"{self.reserved_event} - {self.ticket_id}"

jumpstart/views.py
# python imports
import random
import string
import re
from pprint import pprint

# Django imports
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import View
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic import UpdateView

# form imports
from .forms import LoginForm, RegistrationForm, TicketForm, UpdateForm, CancelTicket

# model imports
from .models import Customer, Ticket, Event


# Django email imports
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags


# Create your views here.


class LoginSignup(View):
    def get(self, request):
        user_session = LoginForm()
        user_signup = RegistrationForm()
        context = {'form': user_session, 'signup': user_signup}
        return render(request, 'registration/login_page.html', context)

    def post(self, request):
        form = LoginForm(request.POST)
        user_signup = RegistrationForm(request.POST, request.FILES)
        if form.is_valid() and 'first_name' not in request.POST.keys():
            user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            if user is None:
                user_signup = RegistrationForm()
                messages.error(request, "Incorrect E-mail or password")
                return render(request, 'registration/login_page.html', {'form': form, 'signup': user_signup})
            print(user, type(user))
            # request.session['user_id'] = user.id
            login(request, user)
            # request.session.save()
            return HttpResponseRedirect(reverse('jumpstart:welcome'))
            # return render(request, 'home_page.html', {'form': form, 'user': user})

        elif user_signup.is_valid():
            print('user sign in form is valid')
            messages.success(request, "Successful Sign-up; Please login", extra_tags='success')
            user_signup.save()
            form = LoginForm(initial={
                'email': user_signup.cleaned_data['email']
            })
            return render(request, 'registration/login_page.html', {'form': form})
        else:
            print('user sign in not valid')
            context = {'form': LoginForm(), 'signup': user_signup}
            return render(request, 'registration/login_page.html', context)


class Welcome(View):
    def get(self, request):
        user_id = request.session.get('_auth_user_id')

        # checking for social auth login directly
        user = request.user
        if user.is_authenticated:
            print(f'Social authentication by {user.username}-{user.email}')
            try:
                user = Customer.objects.get(email=user.email)
            except ObjectDoesNotExist:
                print('Social auth user is not as a customer, making him as a customer')
                try:
                    new_customer = Customer(
                        user=request.user,
                        username=user.username,
                        email=user.email,
                        profile_image='images/profile/gojo.png',
                        password=make_password("".join(random.choices(string.ascii_letters + string.digits, k=8)))
                    )
                    new_customer.save()
                    print(f'Cusomter saved')
                except Exception as e:
                    print(f'Cusomter didnt saved {e}')
                user = Customer.objects.get(email=user.email)

            finally:
                login(request, user, backend='jumpstart.backends.EmailAuthBackend')
                # request.session['_auth_user_id'] = user.id
                return render(request, 'home_page.html', {'user': user})
        elif user_id is not None:
            # print(user_id, type(user_id), request.session.get('_auth_user_id'))
            user = get_object_or_404(Customer, id=user_id)
            # user = User.objects.get(id=request.session.get('user_id'))
            print(user, type(user))
            return render(request, 'home_page.html', {'user': user})
        else:
            return render(request, 'home_page.html', {})


class Profile(View):

    def get(self, request):
        print('in get profile')
        user_id = request.session.get('_auth_user_id')
        user = get_object_or_404(Customer, id=user_id)
        tickets = Ticket.objects.filter(customer=user).order_by('-transaction_timestamp')
        print(tickets)
        cancel_ticket = CancelTicket()
        return render(request, 'profile_page.html', {'user': user, 'tickets': tickets, 'cancel_ticket':cancel_ticket})

    def post(self, request):
        user_id = request.session.get('_auth_user_id')
        print(user_id)
        user = get_object_or_404(Customer, id=user_id)
        # print('in post profile', request.POST.keys())
        if 'ticket_id' in request.POST.keys():
            cancel_ticket = CancelTicket(request.POST)
            if cancel_ticket.is_valid():
                # print('validated')
                get_ticket = Ticket.objects.get(ticket_id=cancel_ticket.cleaned_data['ticket_id'])
                get_ticket.delete()
                tickets = Ticket.objects.filter(customer=user).order_by('-transaction_timestamp')
                messages.success(request, 'ticket deleted')
                return render(request, 'profile_page.html',
                              {'user': user,
                               'tickets': tickets,
                               'cancel_ticket': CancelTicket()})
            else:
                tickets = Ticket.objects.filter(customer=user).order_by('-transaction_timestamp')
                return render(request, 'profile_page.html',
                              {'user': user, 'tickets': tickets, 'cancel_ticket': cancel_ticket})

        # delete the user
        messages.success(request, 'Your account has been deleted.')
        logout(request)
        user.delete()
        return redirect('jumpstart:login')


class UserLogout(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('jumpstart:welcome'))


class CustomerBooking(View):

    def get(self, request):
        user_id = request.session.get('_auth_user_id')
        user = get_object_or_404(Customer, id=user_id)
        print('got', user, messages)
        form = TicketForm()
        events = Event.objects.all()

        return render(request, 'booking_page.html', {'form': form, 'user': user, 'events': events})

    def post(self, request):
        print(f'booking post received')
        form = TicketForm(request.POST)
        user_id = request.session.get('_auth_user_id')
        user = get_object_or_404(Customer, id=user_id)
        events = Event.objects.all()
        if form.is_valid():
            print('valid form')
            form.save(commit=False)
            event_type = form.cleaned_data['event_type']
            customer = user
            reserved_event = form.cleaned_data['event']
            if reserved_event is None:
                reserved_event = form.cleaned_data['event_multi']
            reservation_date = form.cleaned_data['reservation_date']
            reservation_time = form.cleaned_data['reservation_time']
            is_student = form.cleaned_data['is_student']
            university = form.cleaned_data['university']
            adult_tickets = form.cleaned_data['adult_tickets']
            children_tickets = form.cleaned_data['children_tickets']
            total_price = float(form.cleaned_data['total_price'].replace('$', ''))
            address = form.cleaned_data['address']
            city = form.cleaned_data['city']
            province = form.cleaned_data['province']
            phone_number = form.cleaned_data['phone_number']
            ticket_id = "T_" + "".join(random.choices(string.ascii_letters + string.digits, k=4))
            transaction_id = "TX_" + "".join(random.choices(string.ascii_letters + string.digits, k=14))
            # pprint([(x, y) for x, y in form.cleaned_data.items()])

            # print(f'form validated: checking other validaitons:\n{reserved_event}\n{reservation_time}\n{reservation_date}')
            # checking each event capacity for that time
            get_details_from_db = Ticket.objects.filter(
                event_type=event_type,
                reserved_event=reserved_event,
                reservation_time=reservation_time,
                reservation_date=reservation_date
            )
            if get_details_from_db.count() >= 2:
                messages.error(request,
                               f"{reserved_event} event booked full for this slot {reservation_time} on \
                               {reservation_date}. Please choose another slot!")
                return render(request, 'booking_page.html', {'form': form, 'user': user, 'events': events})

            # checking abnormal ticket conditions
            if children_tickets and not adult_tickets:
                if reserved_event.name != 'Arcade Corner':
                    messages.error(request,
                                   f"Atleast 1 adult ticket should be booked for all the events except Arcade Corner")
                    return render(request, 'booking_page.html', {'form': form, 'user': user, 'events': events})
            elif not children_tickets and not adult_tickets:
                messages.error(request,
                               f"Atleast 1 ticket should be booked, Empty booking is not allowed")

jumpstart/templates/base.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    {#    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css'>#}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    {#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">#}
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <title>newhome</title>
    {% compress css %}
        <link type="text/x-scss" href="{% static 'scss/home_page.scss' %}" rel="stylesheet" media="screen">
    {% endcompress %}
    <script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script type="text/javascript" src="{% static 'js/home_page.js' %}"></script>
    <style>
        /* Add fillable effect to navbar links */
        .w3-bar-item {
            position: relative;
        }

        .w3-bar-item::before {
            content: "";
            position: absolute;
            bottom: -3px;
            left: 0;
            width: 100%;
            height: 3px;
            background-color: #000;
            visibility: hidden;
            transform: scaleX(0);
            transition: all 0.3s ease-in-out 0s;
        }

        .w3-bar-item:hover::before {
            visibility: visible;
            transform: scaleX(1);
        }
    </style>
</head>
<body>
<!-- partial:index.partial.html -->
<!--<div class="header" id="top">-->
<!--   <h1>Scroll Down</h1>-->
<!--   <i class="fa fa-angle-down animated bounce"></i>-->
<!--</div>-->
<!-- Navigation Bar -->

<div class="w3-bar w3-white w3-large">
    <a href="#" class="w3-bar-item w3-button w3-red w3-mobile">
        {#      <i class="fa-solid fa-tricycle w3-margin-right"></i>Logo#}
        <i class="fa-brands fa-space-awesome"></i>&nbsp

        Jumpstart
    </a>
    {#  <a href="{% url 'create_booking' %}" class="w3-bar-item w3-button w3-mobile">Book</a>#}
    {% if user.is_authenticated %}
        <a href="{% url 'jumpstart:create_booking' %}" class="w3-bar-item w3-button w3-mobile">
            <i class="fa-solid fa-ticket" style="font-size: 15px"></i>
            Book</a>
    {% else %}
        <a href="{% url 'jumpstart:login' %}" class="w3-bar-item w3-button w3-mobile">
            <i class="fa-solid fa-ticket" style="font-size: 15px"></i>Book</a>
    {% endif %}
    {% block about_n_contact %}
    {% endblock %}
    {#    <a href="#about" class="w3-bar-item w3-button w3-mobile">#}
    {#        <i class="fa-solid fa-circle-info" style="font-size: 15px"></i>About</a>#}
    {#    <a href="#contact" class="w3-bar-item w3-button w3-mobile">#}
    {#        <i class="fa-solid fa-address-card" style="font-size: 15px"></i>Contact</a>#}

    {% if user.is_authenticated %}
        <a href="{% url 'jumpstart:logout' %}" class="w3-bar-item w3-button w3-right w3-light-grey w3-mobile">
            <i class="fa-sharp fa-solid fa-right-to-bracket fa-flip-both" style="font-size: 15px"></i>
            logout</a>
        <a href="{% url 'jumpstart:view_profile' %}"
           class="w3-bar-item w3-button w3-right w3-light-grey w3-mobile">
            Welcome {{ user.username }}</a>
        <img class="w3-light-grey w3-right" src="{{ user.profile_image.url }}"
             style="width:35px; height:35px; margin-top: 5px; border-radius: 10px" alt="My Image">
    {% else %}
        <a href="{% url 'jumpstart:login' %}" class="w3-bar-item w3-button w3-right w3-light-grey w3-mobile">
            <i class="fa-sharp fa-solid fa-right-to-bracket" style="font-size: 15px">
            </i>login</a>

    {% endif %}
    {#  <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-right w3-light-grey w3-mobile">Login/Signup</a>#}
</div>

{% block body_block %}***{% endblock %}

<!-- Footer -->
<footer class="w3-padding-32 w3-black w3-center w3-margin-top">
    <h5>Find Us On</h5>
    <div class="w3-xlarge w3-padding-16">
        <i class="fa-brands fa-facebook w3-hover-opacity"></i>&nbsp
        <i class="fa-brands fa-instagram w3-hover-opacity"></i>&nbsp
        <i class="fa-brands fa-snapchat w3-hover-opacity"></i>&nbsp
        <i class="fa-brands fa-pinterest-p w3-hover-opacity"></i>&nbsp
        <i class="fa-brands fa-twitter w3-hover-opacity"></i>&nbsp
        <i class="fa-brands fa-linkedin-in w3-hover-opacity"></i>
    </div>
</footer>
<!-- partial -->

</body>

jumpstart/templates/profile_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Custom CSS -->
    <style>
        /* Center the user profile pic and info */
        .user-profile {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-top: 2rem;
        }

        .user-profile img {
            width: 150px;
            height: 150px;
            border-radius: 50%;
            object-fit: cover;
            margin-bottom: 1rem;
            border: 3px solid black;
        }

        /* Style the options section */
        .options {
            display: flex;
            justify-content: center;
            gap: 1rem;
            margin-top: 2rem;
        }

        /* Style the orders section */
        .orders {
            margin-top: 2rem;
        }

        .orders table {
            width: 100%;
            text-align: center;
        }

        .orders table thead th {
            font-weight: bold;
            border-bottom: 2px solid #dee2e6;
        }

        .orders table tbody tr:nth-child(even) {
            background-color: #f8f9fa;
        }

        /* Style the update section */
        .update {
            margin-top: 2rem;
        }

        /* Style the delete section */
        .delete {
            margin-top: 2rem;
        }

        .delete button {
            background-color: #dc3545;
            color: white;
            border: none;
        }
        .table-bordered {
  background-color: cornflowerblue; /* replace #fff with your desired color */
}
        .table-bordered td {
  background-color: #fff; /* replace #fff with your desired color */
}
    </style>
</head>

<body style="background-color: lightgrey">
<div class="w3-bar w3-red w3-large">
    <a href="{% url 'jumpstart:welcome' %}" class="w3-bar-item w3-button w3-red w3-mobile"
       style="text-decoration: none">
              <i class="fa-solid fa-tricycle w3-margin-right"></i>
        <i class="fa-brands fa-space-awesome fa-flip"></i>&nbsp

        Jumpstart
    </a>
            <a href="{% url 'jumpstart:create_booking' %}" class="w3-bar-item w3-button w3-mobile">
            <i class="fa-solid fa-ticket" style="font-size: 15px; text-decoration: none"></i>
            Book</a>
    <a href="{% url 'jumpstart:logout' %}" class="w3-bar-item w3-button w3-right w3-mobile">
            <i class="fa-sharp fa-solid fa-right-to-bracket fa-flip-both" style="font-size: 15px; text-decoration: none"></i>
            logout</a>
</div>
{#<div class="d-flex align-items-center justify-content-center" style="background-color: #2e2e2e; height: 10vh;">#}
{#    <a href="{% url 'welcome' %}" style="text-decoration: none">#}
{#  <h1 style="color: darkorange"><i class="fa-brands fa-space-awesome fa-flip" style="color: darkorange"></i>#}
{#      &nbspJumpstart</h1>#}
{#    </a>#}
{#</div>#}

<div class="container" style="width: 1270px; height: 600px">
    <!-- User profile section -->
    <div class="user-profile">
        {#      <img src="https://via.placeholder.com/150" alt="User profile picture">#}
        <img src="{{ user.profile_image.url }}">
        <h2>{{ user.username }}</h2>
        <h6><i class="fa-solid fa-envelope"></i>&nbsp&nbsp{{ user.email }}</h6>
        <h6><i class="fa-sharp fa-solid fa-file-circle-exclamation"></i>
            <strong>username</strong>&nbsp&nbsp{{ user.username }}&nbsp&nbsp
            <strong>first name</strong>&nbsp&nbsp{{ user.first_name }}&nbsp&nbsp
            <strong>last name</strong>&nbsp&nbsp{{ user.last_name }}&nbsp&nbsp
        </h6>
    </div>
    <hr/>

    <!-- Options section -->
    <div class="options">
{#        <a href="#orders" class="btn btn-primary">View Orders</a>#}
{#        <a href="#update" class="btn btn-secondary">Update Profile</a>#}
        <a href="{% url 'jumpstart:profile_update' %}"><button type="submit" class="btn btn-secondary">Update Profile</button></a>
        <a href="#delete" class="btn btn-danger">Delete Account</a>
        <a href="#cancel" class="btn btn-info">Cancel Ticket</a>
{#        <a href="{% url 'logout' %}" class="btn btn-info">#}
{#            <i class="fa-sharp fa-solid fa-right-to-bracket fa-flip-both" style="font-size: 20px"></i>#}
{#            logout</a>#}
    </div>
    <div style="margin-top: 25px">
    {% if form.errors %}
        <div class="alert alert-danger">
            {% for field in form %}
                {% if field.errors %}
                    <h6><i class="fa-solid fa-triangle-exclamation fa-shake"></i>&nbsp&nbsp{{ field.label }}</h6>
                    <ul>
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
        {% if messages %}
            {% for msg in messages %}
{#                {% if msg.tags == 'error' %}#}
{#                    <div class="alert alert-danger">#}
{#                        <h6><i class="fa-solid fa-times"></i> {{ msg }} {{ form.phone_number.error }}</h6>#}
{#                    </div>#}
                {% if msg.tags == 'success' %}
                    <div class="alert alert-success">
                        <h6><i class="fa-solid fa-check"></i> {{ msg }}</h6>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>


    <!-- Orders section -->
    <div id="orders" class="orders">
        <h3>Recent Orders</h3>
        <table class="table table-hover table-bordered" style="border-radius: 10px">
            <thead>
            <tr>
                <th>Ticket ID</th>
                <th>Transaction Time </th>
                <th>Type of Event</th>
                <th>Event Booked</th>
                <th>Reservation Date</th>
                <th>Reserved slot</th>
                <th>Adult Tickets</th>
                <th>Child Tickets</th>
                <th>Total Price</th>
            </tr>
            </thead>
            <tbody>
            {% for ticket in tickets %}
                <tr>
                    <td>{{ ticket.ticket_id }}</td>
                    <td>{{ ticket.transaction_timestamp }}</td>
                    <td>{{ ticket.event_type }}</td>
                    <td>{{ ticket.reserved_event }}</td>
                    <td>{{ ticket.reservation_date }}</td>
                    <td>{{ ticket.reservation_time }}</td>
                    <td>{{ ticket.adult_tickets }}</td>
                    <td>{{ ticket.children_tickets }}</td>
                    <td>${{ ticket.total_price }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Update section -->
    {% if form %}
        <div id="update" class="update">
            <h3>Update Profile</h3>
            {% if form.errors %}
                <div class="alert alert-danger">
                    {% for error in form.errors %}
                        <h6><i class="fa-solid fa-triangle-exclamation fa-shake"></i>
                            &nbsp&nbsp{{ error }}</h6>
                    {% endfor %}
                </div>
            {% endif %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save Changes</button>
                {#                <button type="submit">Save changes</button>#}
            </form>
            <a href="{% url 'jumpstart:view_profile' %}">
                    <button type="submit" class="btn btn-dark"  style="margin-top: 3px">Cancel Changes</button>
            </a>
        </div>
    {% endif %}

    <!-- Cancel section -->
    {% if cancel_ticket %}
        <div id="cancel" class="update">
            <h3>Cancel Ticket</h3>
            <p>Please enter the ticket to be cancelled</p>
            <form method="post">
                {% csrf_token %}
                {{ cancel_ticket.as_p }}
                <button type="submit" class="btn btn-primary">Cancel Ticket</button>
                {#                <button type="submit">Save changes</button>#}
            </form>
        </div>
    {% endif %}
    <!-- Delete section -->
    <form id="delete-form" method="POST" action="">
        {% csrf_token %}
{#        <div id="delete" class="delete" onclick="document.getElementById('delete-form').submit()">#}
            <div id="delete" class="delete">
            <h3>Delete Account</h3>
            <p>Are you sure you want to delete your account? This action cannot be undone.</p>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
                Delete Account
            </button>

            <!-- Delete Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Confirm Account Deletion</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure you want to delete your account? This action cannot be undone.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-bs-dismiss="modal">No, Cancel</button>
                            <button type="button" class="btn btn-danger">Yes, Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/profile_page.js' %}"></script>
</body>
</html>
           